## extremely simple deployment

apiVersion: apps/v1
kind: Deployment # defines that this is a deployment
metadata:
  name: sdxl-kube # "Create a Deployment named sdxl-kube"
spec: # defining owned Pods / Configuration of Pods
  replicas: 1 
  selector:
    matchLabels:
      app: sdxl-kube # assigns Pods labelled "sdxl-kube" to this deployment 
  template: # Pod configuration
    metadata: 
      labels:
        app: sdxl-kube # every pod created will have hte label sdxl-kube

        # selector is how deployment finds labelled Pods, template is how deployment labels created Pods
    spec:
      containers:
        - name: sdxl-kube
          # python fastAPI image right now, will adjust when CUDA is involved
          image: hello-world-test
          # we're using a local image right now, adjust later
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          
          # the probes go underneath the Container, since it's using our Pod endpoints
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          # use the /health endpoint, check every 10s
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service # defines the service for the Pods (stable entrypoint)
metadata:
  name: sdxl-kube-python-api # service DNS 
spec:
  type: ClusterIP
  selector:
    app: sdxl-kube # route traffic to Pods labelled sdxl-kube
  ports:
    - port: 80 # external port 
      targetPort: 8080 # container port
